# Generated by Django 4.2.6 on 2023-10-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('char', models.CharField(max_length=50)),
                ('thenme', models.CharField(max_length=50)),
                ('dirnme', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='todos',
        ),
    ]
